# Generated by Django 4.0.1 on 2022-01-29 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('date_hired', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('position', models.IntegerField(choices=[(0, 'Ceo'), (1, 'President'), (2, 'Director'), (3, 'Manager'), (4, 'Employee')])),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='core.worker')),
            ],
        ),
    ]
